name: EasyPets
main: PT\Loader
author: TutoGamerWalid
version: 1.0
description: Your pets follow you.
api: [3.0.0, 4.0.0]

permissions:
 pets.command.use:
  default: true
  description: "Allow to use the pets"
