name: EasyPets
main: PT\Loader
author: TutoGamerWalid
version: 1.0
description: Your pets follow you.
api: 3.0.0

permissions:
 pets.use.command:
  default: true
  description: "Allow to use the pets"
